import { useWallet } from "@/hooks/use-wallet";

/**
 * Reports how proofs get generated for this session.
 *
 * Mandate delegates proving to the connected wallet via the DApp Connector's
 * `getProvingProvider` (see `createProviders` in the api package). The wallet
 * uses whatever prover its user has configured, so this app requires no proof
 * server of its own and a visitor needs nothing running locally.
 *
 * This replaced an earlier badge that pinged a proof server URL guessed by
 * swapping the substrate node's port to 6300 — that reflected the deprecated
 * `Configuration.proverServerUri` model and reported a status unrelated to how
 * proving actually happens here.
 */
export function ProvingMode() {
  const { status } = useWallet();

  if (status !== "connected") return null;

  return (
    <span
      className="flex items-center gap-1.5 border border-border px-2.5 py-1 text-xs"
      title="Proofs are generated by your wallet's configured prover"
    >
      <span className="h-1.5 w-1.5 bg-foreground" aria-hidden />
      Proving: wallet
    </span>
  );
}
